### ISSUE TITLE
compile error: mp_raise_ValueError issue

### ISSUE THREAD

**Issue by hklang10** [russhughes/st7789_mpy#1]
mp_raise_ValueError() has been changed in Micropython master.

See commit at https://github.com/micropython/micropython/commit/def76fe4d9bbc2c342594dc05861b24d7165d274   and pr at https://github.com/micropython/micropython/pull/5168/commits

line 717 and line 722 of st7789.c need to be modified.
```
mp_raise_ValueError("Unsupported display. Only 240x240 and 135x240 are supported");
mp_raise_ValueError("must specify all of reset/dc pins");
```
now needs to be 
```
mp_raise_ValueError(MP_ERROR_TEXT("Unsupported display. Only 240x240 and 135x240 are supported"));
mp_raise_ValueError(MP_ERROR_TEXT("must specify all of reset/dc pins"));
```

**Comment by russhughes** [comment]
Thanks for the report, fixed the issue and updated firmware.bin to MicroPython v1.12-464-gcae77daf0
