### ISSUE TITLE
st7789.ST7789.color_order not present in precompiled RP2 build

### ISSUE THREAD

**Issue by QuantumFluxCapacitor** [russhughes/st7789_mpy#100]
Assuming it should be present in st7789.ST7789, color_order is not recognized by the interpreter, nor is it listed in a dir command. I am trying to get the color order right for a 128x128 ST7735 display and thus stumbled upon this.

**Comment by russhughes** [comment]
I’ll take a look at it.

**Comment by QuantumFluxCapacitor** [comment]
Thank you for the clarification.
