### ISSUE TITLE
polygon angle

### ISSUE THREAD

**Issue by funjspi** [russhughes/st7789_mpy#108]
I did not build the driver myself, I'm using the pre-compiled UF2 firmware.

When I try to place a polygon, eg:
`lcd.polygon([(0,25),(0,75),(10,75),(10,100),(200,100),(200,0),(10,0),(10,25),(0,25)],20,72,st7789.WHITE,180,0,0)`

`lcd` is the instance of the driver I have initiated.
`180` is the angle I want to rotate the polygon.

It has no effect.

**Comment by russhughes** [comment]
Angles should be specified in radians (180*0.017453 or 3.141593) and not degrees. https://www.inchcalculator.com/convert/degree-to-radian/

**Comment by funjspi** [comment]
Thank you!
