### ISSUE TITLE
ST7789 versus ST7789V

### ISSUE THREAD

**Issue by StarfighterLily** [russhughes/st7789_mpy#111]
Is the ST7789 code here compatible with the V? I'll try this out but with great hesitation; I don't want to break anything. I also don't know much of anything about this sort of thing so I'm asking in case it fails and I don't know how to adapt it for my hardware lol.

Edit: I flashed it, tinkered, and broke stuff so I flashed my backup while I learn more ;)

**Comment by russhughes** [comment]
It should be fine as long as it is wired correctly.

**Comment by StarfighterLily** [comment]
I can't get it to work =/ I guess this is just out of my league
