### ISSUE TITLE
How to scroll horizontal？

### ISSUE THREAD

**Issue by jd3096-mpy** [russhughes/st7789_mpy#129]
Like micropython offical method ,we can use 
FrameBuffer.scroll(xstep, ystep)[¶](https://docs.micropython.org/en/latest/library/framebuf.html?highlight=scroll#framebuf.FrameBuffer.scroll)
So it can easily scroll horizontal and Vertical.

In this repo, I found the vscrdef(tfa, height, bfa) vscsad(vssa) method ,they only can scroll  vertical,I tried to set rotation=1, the screen direction rotation 90 degree ,but scroll direction is still unchanged.
So,how to to scroll horizontal?

**Comment by russhughes** [comment]
The vscsad is a hardware scroll that only scroll in the one axis.
