### ISSUE TITLE
Slow PNG Drawing on ESP-WROOM-32 even while using buffer_size option

### ISSUE THREAD

**Issue by estcap2** [russhughes/st7789_mpy#151]
Hi,
I'm using the precompiled GENERIC-7789 firmware with an ESP-WROOM-32 board and a 128x128 SPI TFT screen.
While the PNGs display correctly, there's noticeable slow line-by-line drawing for fullscreen PNGs, as described in the documentation.

Expected Behavior:
I expected a more responsive rendering of fullscreen PNGs using the ST7789 driver, especially with the use of the `buffer_size` option to optimize performance.

Actual Behavior:
The `png()` function seems to perform a slow line-by-line drawing process despite setting the buffer_size. I'm wondering if there might be a misunderstanding on my part about the usage of the framebuffer or if the `png()` function doesn't leverage it.

My code snippet:
```python
import machine
import st7789
spi = machine.SPI(2, baudrate=40000000, polarity=0, phase=0, sck=machine.Pin(14), mosi=machine.Pin(13), miso=machine.Pin(12) )
display = st7789.ST7789(spi,
                        128,
                        128,
                        reset=machine.Pin(17, machine.Pin.OUT),
                        dc=machine.Pin(16, machine.Pin.OUT),
                        cs=machine.Pin(18, machine.Pin.OUT),
                        color_order=st7789.BGR,
                        inversion=False,
                        buffer_size=128*128*2
                        )
display.init()
display.png('test.png', 0, 0)
```

This results in what is described above and in the documentation, a slow line by line drawing process.
Does the ST7789 driver already utilize a framebuffer? Or is there a specific reason why the `png()` function might not utilize it, resulting in the observed slow drawing?

I appreciate any insights or assistance in understanding whether the framebuffer is used and how the `png()` function interacts with it. Thank you for your time and support.

**Comment by russhughes** [comment]
The PNG method always draws a line at a time when not using masking for transparency. When using masking for transparency, it will draw shorter line segments.  This driver does not use a full-screen buffer.
