### ISSUE TITLE
How to use with CircuitPython?

### ISSUE THREAD

**Issue by RyannDaGreat** [russhughes/st7789_mpy#16]
Hi, thank you for making this library - it seems promising!
Is there a way to get this to work with CircuitPython (which is a fork of MicroPython)? 
And if so, can we get this code running on the Teensy 4.0 with CircuitPython?
My project involves creating a display with scrolling text, and this library seems faster than the default options
Thank you,
Ryan

**Comment by russhughes** [comment]
The driver would have to be changed to work with CircuitPython's hardware abstraction layer.   I haven't used CircuitPython since they dropped support for the ESP boards so I don't know how much work it would take to support CircuitPython.
