### ISSUE TITLE
ST7789.bitmap(bitmap, x , y) is not work

### ISSUE THREAD

**Issue by HorwinHe** [russhughes/st7789_mpy#22]
hi, bro, I use the ST7789.bitmap(bitmap, x , y) to display bitmap, like ''spi = machine.SPI(2, baudrate=2000000000, polarity=1, sck=machine.Pin(18), mosi=machine.Pin(23))  display = st7789.ST7789(spi, 135, 240, reset=machine.Pin(4, machine.Pin.OUT),dc=machine.Pin(2, machine.Pin.OUT),cs=machine.Pin(19,machine.Pin.OUT))'' when I use display.bitmap('6.bmp',0,0) ,it not work, and i not found the imgtobitmap.py, can you tell me how to use it. thanks.

**Comment by russhughes** [comment]
I've updated the examples and fixed the missing utils files. `bitmap` does not read bmp files. See the `toasters.py` example to see how `bitmap` works. The `maketoast` script in `utils` shows the method I used to convert a sprite bitmap into `bitmap` modules for the `toasters` demo.
