### ISSUE TITLE
jpg (96x60) ok but position x,y ko 

### ISSUE THREAD

**Issue by picpic020960** [russhughes/st7789_mpy#29]
Bonjour Russ ,
try png to jpg online converters :OK (but not all)
then test with jpg.py 
the icon is displayed at 0,0 position
but  when change to x,y the icon is always at 0,0
how to debug ?
thanks for help
Regards

PS : (so can't test more one jpg on the display ...)

**Comment by russhughes** [comment]
I added conversion instructions and another jpg example for the T-Display.  What device are you using?

**Comment by picpic020960** [comment]
Thanks Russ
Will test tomorrow

**Comment by russhughes** [comment]
The buffer should be large enough to hold the bitmap (height * width * 2) when using the FAST method.  You can leave the buffer_size out and the driver will allocate and free memory as needed. Using the buffer_size trades memory for speed.

I’ll be updating the driver to work with the new Cmake build system this week.

**Comment by russhughes** [comment]
The driver can now be compiled using the new CMake build system.
