### ISSUE TITLE
[resolved]"Clone this module alongside the MPY sources:  $ git clone ..."  ???

### ISSUE THREAD

**Issue by picpic020960** [russhughes/st7789_mpy#30]
Bonjour Russ ,
I try to compile st7789_mpy module with cmake micropython version.
cmake micropython is OK
but for clone st7789_mpy repo I don't know where : 
what folder ? 
new folder ?
frozen_mpy ?
what is 'user modules directory' ?
Thank's for help
Regards

**Comment by russhughes** [comment]
cd your_directory_you_want_to_use
git clone https://github.com/micropython/micropython.git
git clone https://github.com/russhughes/st7789_mpy.git

Making both repos subdirectories of the same directory for example:
/home/russ/micropython
/home/russ/st7789_mpy

The 'user modules directory'  can be used when you have several C external modules you want to include at the same time. You  could with the old make build system (not sure if this works with the cmake build system) create a directory and place several modules in it . You could then specify the directory as the user modules directory and the build system would include each of the modules. 

for example:
/home/russ/my_micropython-modules/st7789_mpy
/home/russ/my_micropython-modules/ili9342c_mpy

**Comment by picpic020960** [comment]
Thanks Russ
I go on
