### ISSUE TITLE
Compilation for the Raspberry Pico

### ISSUE THREAD

**Issue by aleggon** [russhughes/st7789_mpy#35]
Hi, friend. 
I tried to compile for the Pico with make USER_C_MODULES=../../../../st7789_mpy/st7789/micropython.cmake but got this error message:

Found User C Module(s): 
-- Configuring incomplete, errors occurred!
See also "/home/alexandre/micropython/ports/rp2/build-PICO/CMakeFiles/CMakeOutput.log".
See also "/home/alexandre/micropython/ports/rp2/build-PICO/CMakeFiles/CMakeError.log".
make: *** [Makefile:18: all] Error 1

Can you show me how to build the firmware for this board?
Thank you!

**Comment by russhughes** [comment]
The PICO port requires one less "../" then other ports. Try USER_C_MODULES=../../../st7789_mpy/st7789/micropython.cmake or use the full pathname to the micropython.cmake file. For example: USER_C_MODULES=/home/alexandre/st7789_mpy/st7789/micropython.cmake
