### ISSUE TITLE
tft.jpg SLOW method ignores offsets

### ISSUE THREAD

**Issue by RSTnuts** [russhughes/st7789_mpy#38]
tft.jpg("15.jpg", 22, 55, st7789.FAST) - puts the image in the correct place (but I run out of memory eventually)

tft.jpg("15.jpg", 22, 55, st7789.SLOW) - ignores the offsets, making them effectively 0,0 - but the code works indefinitely

Fumbling my way through micropython so clueless as to how to correct this.

**Comment by russhughes** [comment]
This is definitely a bug in the driver.  I'll see if I can fix it tonight.
