### ISSUE TITLE
LVGL driver?

### ISSUE THREAD

**Issue by jdtsmith** [russhughes/st7789_mpy#42]
This is not really an issue but just a discussion of the need for LVGL to include an ST7789 driver.  I _think_ this driver should be almost identical to the ST7735, which [they already have a driver for](https://github.com/lvgl/lv_drivers/blob/master/display/ST7565.c).  In LVGL display drivers [do almost nothing](https://docs.lvgl.io/latest/en/html/porting/display.html#display-driver) except arrange to transfer buffer ranges to screen areas.  LVGL handles the rest. 

An advantage of this approach is that you'd gain immediate access to all the rich and well-debugged C primitives for drawing buttons, fonts, widgets, shapes, animations, etc. of [LVGL from micropython](https://docs.lvgl.io/latest/en/html/get-started/micropython.html#).  Their claim that "64 kB flash and 8 kB RAM is enough for a simple user interface" is pretty appealing.  

I suspect you and @devbis are well-situated to make quick work of this, and wondered if you might have time and be interested!

**Comment by russhughes** [comment]
See https://github.com/russhughes/lv_st7789 for the LVGL driver source and a pre-compiled firmware.bin that will run on an GENERIC ESP device as well as several examples that run on the TTGO T-Display device.

**Comment by jdtsmith** [comment]
Excellent!  Will give it a try.  What size buffer did you settle on? Looks like double-buffering ~1/10th the screen is a good compromise.

**Comment by russhughes** [comment]
I used a single buffer with a factor of 4 (1/4 screen size) and it looked good.  Larger buffers are faster, smaller use less memory. You can adjust the size using the factor= parameter.

**Comment by bwees** [comment]
https://github.com/russhughes/lv_st7789 no longer exists, does it not work anymore? does anyone know if I can just pump the frame buffer in some way to this library to get it to work?

**Comment by russhughes** [comment]
It's now included in the LVGL ili9xxx Hybrid driver.

**Comment by bwees** [comment]
This driver? https://github.com/lvgl/lv_binding_micropython/blob/master/driver/esp32/ili9XXX.py

Brandon Wees

**Comment by russhughes** [comment]
Yes, it's slightly different, but that is where it ended up.

**Comment by bwees** [comment]
Awesome thanks for the help

Brandon Wees
