### ISSUE TITLE
Question on how to reset scroll position

### ISSUE THREAD

**Issue by erongd** [russhughes/st7789_mpy#59]
I am trying to use vscrdef and vscrad function to implement scrolling. It is working as intended.

However after done scrolling content across the screen, I will be performing some other display on the screen. I was wondering how to reset the scrolling in such a way 0, 0 will return to left top. Otherwise my follow on optioning starts in somewhere in the middle of the screen. Right now the only way I know to do is initials the screen again.

**Comment by russhughes** [comment]
You can clear the display using fill(0) then set the vscsad to the tfa or set vscsad to 0 if the display has no tfa.

**Comment by erongd** [comment]
Set to TFA works, thanks.
