### ISSUE TITLE
Add syntax checking and type checking 

### ISSUE THREAD

**Issue by vertexi** [russhughes/st7789_mpy#61]
This library is cool and fast.
And when I use IDE like Pycharm to write code, I found that I can't do some syntax checking and type checking.
So I write a st7789.pyi file to support syntax checking. I wondering how can I contribute this change to this library.

**Comment by russhughes** [comment]
You can use a pull request or attach the file to a comment.

**Comment by vertexi** [comment]
[st7789.zip](https://github.com/russhughes/st7789_mpy/files/8104437/st7789.zip)

There you are.:smile:

**Comment by russhughes** [comment]
Thanks for the pyi file: 30d73e74f39897d5f115cf7aeea9150ab7c76baf
