### ISSUE TITLE
St7789 fuctions

### ISSUE THREAD

**Issue by cyberjunkiefr** [russhughes/st7789_mpy#66]
Hello everybody,
This might so much of an issue, because I have it working on a TTGO-T8-DISPLAY ESP32.
The thing I'm missing is some kind of documentation of the functions this driver has.
If somebody has an link to some information that would clear my issue.
In the meanwhile I thank you all for the help

Roel Jaspers

**Comment by russhughes** [comment]
See https://github.com/russhughes/st7789_mpy/blob/master/README.md for information.

**Comment by cyberjunkiefr** [comment]
Thanks a lot!
