### ISSUE TITLE
How much fps does the driver give with lvgl?

### ISSUE THREAD

**Issue by OPHoperHPO** [russhughes/st7789_mpy#7]
Hi, @russhughes. 

I am making [micropython port](https://github.com/OPHoperHPO/lilygo-ttgo-twatch-2020-micropython) for lilygo ttgo t-watch-2020 v1 watch and now i am looking for fast driver for the display in this watch. I came across this driver and have some questions regarding it. Have you tested this display driver paired with lvgl? If you tested it, could you tell me how many fps it gives when rendering and updating the lvgl interface?

**Comment by russhughes** [comment]
I haven't used lvgl yet. It looks interesting, I'll check it out.
