### ISSUE TITLE
Sorry for the dumb question

### ISSUE THREAD

**Issue by yomasa** [russhughes/st7789_mpy#78]
All the fonts on the display are mirrored backwards I'm using a 240 by 320 display,  how do I fix that?

**Comment by russhughes** [comment]
You can set the direction and orientation of the drawing by changing the MADCTL register value using the madctl method and the MADCTL_M? constants. The cfg_helper.py program in the examples folder can be helpfull in determining the MADCTL value(s) you need for your display.

**Comment by russhughes** [comment]
See: https://github.com/russhughes/st7789_mpy#madctl-examples for example MADCTL values.
