### ISSUE TITLE
how to show png transparent files?

### ISSUE THREAD

**Issue by jd3096-mpy** [russhughes/st7789_mpy#83]
Thanks for providing us a fast dirver! It's very useful!
I notice there ia a method "write" to show transparent fonts ,I tried, it worked.
but is there a way to show png transparent files?

**Comment by russhughes** [comment]
There is no support for png files in the driver.

**Comment by jd3096-mpy** [comment]
> There is no support for png files in the driver.

Thanks,I will try other way to achieve transparent.
Such as prepare mask images.

**Comment by russhughes** [comment]
PNG support with Alpha channel masking is now in the driver using the https://github.com/kikuchan/pngle library. It is lightly tested but works with pngle compatible PNGs.
