### ISSUE TITLE
Are there plans to support the 8080 bus?

### ISSUE THREAD

**Issue by liangyingy** [russhughes/st7789_mpy#88]

**Comment by russhughes** [comment]
Yes.

**Comment by russhughes** [comment]
https://github.com/russhughes/st7789s3_mpy

**Comment by liangyingy** [comment]
Great. My idea is to implement an 8080 class. Then pass its instance as a parameter to st7789.ST7789.

**Comment by russhughes** [comment]
I was thinking about a module that implemented Dedicated GPIO (https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/dedic_gpio.html) would be ideal.  After researching it, I found Espresstif has something (https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/lcd.html) that looks interesting.

**Comment by liangyingy** [comment]
I am now implementing the 8080 module of st7789 on the basis of esp_lcd.

**Comment by russhughes** [comment]
Looks fast.
